name: 🐞 Issue
description: Create a report
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: qa
    attributes:
      label: Check that this is really a bug
      description: For Q&A open go to [StackOverflow](https://stackoverflow.com/)
      options:
        - label: I confirm
          required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction link
      description: Please provide a link to a repo that can reproduce the problem you ran into. A reproduction is required unless you are absolutely sure that the issue is obvious and the provided information is enough to understand the problem. If a report is vague (e.g. just a generic error message) and has no reproduction, it will receive a "missing demo" label. If no reproduction is provided after 3 days, it will be auto-closed.
      placeholder: 'https://codesandbox.io/..'
    validations:
      required: true
  - type: textarea
    id: descr
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A concise description of what you're experiencing
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: input
    id: injectcssextension
    attributes:
      label: vitejs-plugin-inject-css version
      description: Exact release version or commit hash
      placeholder: e.g 0.0.1
    validations:
      required: true
  - type: input
    id: viteversion
    attributes:
      label: ViteJs version
      description: Exact release version or commit hash
      placeholder: e.g 2.7.12
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [docs](https://github.com/cutterbl/vitejs-plugin-inject-css/blob/master/README.md).
          required: true
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
          required: true
        - label: Make sure this is a moment-extension issue and not a framework-specific or moment issue
          required: true
  - type: checkboxes
    id: pr
    attributes:
      label: Would you like to open a PR for this bug?
      description: Before starting to work on PR it is recommended to get maintainers approval
      options:
        - label: I'm willing to open a PR
          required: false