# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'README.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    name: release
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build fresh for new package with updated version numbers
        run: yarn build

      - name: Setup git creds
        env:
          config_email: ${{secrets.GIT_CONFIG_EMAIL}}
          config_un: ${{secrets.GIT_CONFIG_USERNAME}}
        run: |
          git config --local user.email ${config_email}
          git config --local user.name ${config_un}

      - name: Create the release
        run: yarn release

      - uses: JS-DevTools/npm-publish@v1
        with:
          access: 'public'
          token: ${{secrets.NPM_TOKEN}}
